"""Pixel-art sprites for the Kivy frontend, as data (no Kivy import, so tests can check it).

Each sprite is 8 pixels wide and 16 tall, the ~1:2 shape of a grid cell, and maps a
sprite id from the game (tile type, "depleted", "player", "gem", "bag" or an enemy
name) to rows of palette letters. "." is transparent. Textures with 8 rows repeat
them to fill 16. "gem" is drawn in grays so the game can tint it with the gem's color.
"""

WIDTH, HEIGHT = 8, 16

PALETTE = {
    ".": None,
    # grass, trees
    "G": (38, 112, 38),
    "g": (72, 158, 62),
    "y": (128, 204, 92),
    "T": (20, 78, 24),
    "t": (44, 128, 44),
    "w": (104, 64, 24),
    # path, dirt, sand, town
    "p": (150, 116, 62),
    "P": (122, 92, 46),
    "d": (110, 76, 42),
    "D": (80, 54, 30),
    "k": (192, 172, 112),
    "K": (160, 140, 90),
    "q": (124, 98, 54),
    "Q": (92, 72, 38),
    # rock, ore
    "R": (84, 84, 88),
    "r": (136, 136, 140),
    "h": (192, 192, 196),
    "o": (255, 212, 0),
    "a": (110, 200, 255),
    "A": (200, 240, 255),
    # water
    "b": (36, 104, 196),
    "B": (96, 164, 240),
    "n": (10, 30, 118),
    "N": (32, 62, 160),
    # cave
    "c": (44, 34, 24),
    "C": (64, 50, 34),
    "x": (74, 52, 26),
    "X": (36, 26, 12),
    # worked-out ground
    "e": (56, 46, 36),
    "E": (34, 28, 20),
    # buildings
    "m": (172, 122, 62),
    "M": (168, 40, 30),
    "z": (52, 30, 10),
    "$": (255, 204, 0),
    "W": (240, 240, 240),
    "L": (196, 196, 196),
    "l": (140, 140, 140),
    "v": (86, 60, 140),
    "V": (140, 110, 220),
    # people and creatures
    "H": (122, 70, 20),
    "s": (240, 190, 140),
    "u": (52, 92, 204),
    "j": (60, 50, 42),
    "Z": (12, 12, 12),
    "U": (120, 78, 36),
    "O": (82, 50, 22),
    "i": (120, 30, 160),
    "I": (176, 92, 220),
    "f": (90, 180, 50),
    "F": (50, 120, 30),
    "S": (220, 40, 40),
}

SPRITES = {
    # ── Ground (fills the cell) ───────────────────────────────────────────────
    "grass": [
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
        "GGGgGGGG",
        "GGGGGGGG",
        "GgGGGGGG",
        "GGGGGgGG",
        "GGGGGGGG",
    ],
    "tree": [
        "GGGtTGGG",
        "GGtttTGG",
        "GttTttTG",
        "GtttTttG",
        "ttTtttTt",
        "tTttTttT",
        "tttTtttt",
        "GtTttTtG",
        "GGtttTGG",
        "GGGwwGGG",
        "GGGwwGGG",
        "GGGwwGGG",
        "GGwwwwGG",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
    ],
    "path": [
        "pppppppp",
        "ppPppppp",
        "pppppPpp",
        "pppppppp",
        "pPpppppp",
        "ppppppPp",
        "pppPpppp",
        "pppppppp",
    ],
    "rock": [
        "RRRRRRRR",
        "RRRhRRRR",
        "RRhrrRRR",
        "RhrrrrRR",
        "hrrrrrrR",
        "rrrRrrrr",
        "rrRRRrrr",
        "RRRRRRRR",
        "RRRRRhRR",
        "RRRRhrrR",
        "RRRhrrrr",
        "RRhrrrRr",
        "RhrrrRRr",
        "hrrrrrrr",
        "rrrrrrrr",
        "RRRRRRRR",
    ],
    "ore": [
        "rrrrrrrr",
        "rroRrrrr",
        "rRoorrrr",
        "rrrrrrRr",
        "rrrrroor",
        "rrRrrorr",
        "rrrrrrrr",
        "rRrrrrRr",
    ],
    "dirt": [
        "dddddddd",
        "ddDddddd",
        "ddddddDd",
        "dddddddd",
        "dDdddddd",
        "dddddDdd",
        "ddDddddd",
        "dddddddd",
    ],
    "shallow": [
        "bbbbbbbb",
        "bbBBbbbb",
        "bbbbbbbb",
        "bbbbbBBb",
        "bbbbbbbb",
        "bBBbbbbb",
        "bbbbbbbb",
        "bbbbBBbb",
    ],
    "bank": [
        "kkkkkkkk",
        "kKkkkkkk",
        "kkkkkKkk",
        "kkkkkkkk",
        "kkKkkkkk",
        "kkkkkkKk",
        "kkkkkkkk",
        "Kkkkkkkk",
    ],
    "deep": [
        "nnnnnnnn",
        "nnNNnnnn",
        "nnnnnnnn",
        "nnnnnNNn",
        "nnnnnnnn",
        "nNNnnnnn",
        "nnnnnnnn",
        "nnnnNNnn",
    ],
    "cave_floor": [
        "cccccccc",
        "cCcccccc",
        "ccccccCc",
        "cccccccc",
        "cccCcccc",
        "cccccccc",
        "cCcccccC",
        "cccccccc",
    ],
    "cave_wall": [
        "XXXXXXXX",
        "xxxXxxxx",
        "xxxXxxxx",
        "XXXXXXXX",
        "xXxxxxXx",
        "xXxxxxXx",
        "XXXXXXXX",
        "xxxxXxxx",
    ],
    "rich_ore": [
        "cccccccc",
        "ccAccccc",
        "caaacccc",
        "ccaccCcc",
        "cccccAcc",
        "ccccaaac",
        "cCcccacc",
        "cccccccc",
    ],
    "town": [
        "qqqqqqqQ",
        "qqqqqqqQ",
        "qqqqqqqQ",
        "QQQQQQQQ",
        "qqqQqqqq",
        "qqqQqqqq",
        "qqqQqqqq",
        "QQQQQQQQ",
    ],
    "shop": [
        "qqqqqqqq",
        "qqqqqqqq",
        "qqMMMMqq",
        "qMMMMMMq",
        "MMMMMMMM",
        "mmmmmmmm",
        "mWWmm$$m",
        "mWWmm$$m",
        "mmmmmmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
    ],
    "lapidary": [
        "qqqqqqqq",
        "qqqqqqqq",
        "qqvvvvqq",
        "qvvvvvvq",
        "vvvvvvvv",
        "mmmmmmmm",
        "mmmVVmmm",
        "mmVVVVmm",
        "mmmVVmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
    ],
    "save": [
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqWqqqq",
        "qqqWWqqq",
        "qqqWWWqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqLLLLqq",
        "qLllllLq",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
    ],
    "mineable_grass": [
        "GGGGGGGG",
        "GGGyyGGG",
        "GGygGyGG",
        "GygGGgyG",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
        "GGGGGGGG",
    ],
    "mineable_dirt": [
        "dddddddd",
        "ddDddDdd",
        "dddDDddd",
        "dddDDddd",
        "ddDddDdd",
        "dddddddd",
        "dDdddddd",
        "dddddddd",
    ],
    "mineable_rock": [
        "rrrrrrrr",
        "rrRrrrrr",
        "rrrRrrhr",
        "rRrrRrrr",
        "rrRrrRrr",
        "rhrrrrRr",
        "rrrrrRrr",
        "rrrrrrrr",
    ],
    "stream": [
        "bbbbbbbb",
        "bBBbbbbb",
        "bbbBBbbb",
        "bbbbbBBb",
        "bbbbbbbb",
        "bBBbbbbb",
        "bbbBBbbb",
        "bbbbbBBb",
    ],
    "lake": [
        "NNNNNNNN",
        "NNbNNNNN",
        "NNNNNNNN",
        "NNNNNbNN",
        "NNNNNNNN",
        "NbNNNNNN",
        "NNNNNNNN",
        "NNNNbNNN",
    ],
    "depleted": [
        "eeeeeeee",
        "eeEeeeee",
        "eEEEeeee",
        "eeEeeeEe",
        "eeeeeEEE",
        "eeeeeeEe",
        "eeEeeeee",
        "eeeeeeee",
    ],
    # ── Objects (drawn over the ground) ───────────────────────────────────────
    "player": [
        "........",
        "........",
        "..HHHH..",
        ".HHHHHH.",
        "..ssss..",
        "..sZsZ..",
        "..ssss..",
        "...ss...",
        ".uuuuuu.",
        "s.uuuu.s",
        "s.uuuu.s",
        "..uuuu..",
        "..jjjj..",
        "..j..j..",
        "..j..j..",
        ".ZZ..ZZ.",
    ],
    "gem": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "..WWWW..",
        ".WLWWLW.",
        "LLLLLLLL",
        ".LlLLlL.",
        "..lLLl..",
        "...ll...",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "bag": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "...UU...",
        "..U..U..",
        "...UU...",
        "..UUUU..",
        ".UUUUUU.",
        ".UUO$UU.",
        ".UUUUUU.",
        "..UUUU..",
        "........",
        "........",
        "........",
    ],
    # ── Icons (floating event text) ───────────────────────────────────────────
    "heart": [
        "........",
        "........",
        "........",
        "........",
        "........",
        ".SS..SS.",
        "SWSSSSSS",
        "SSSSSSSS",
        "SSSSSSSS",
        ".SSSSSS.",
        "..SSSS..",
        "...SS...",
        "........",
        "........",
        "........",
        "........",
    ],
    "bear": [
        "........",
        "........",
        "........",
        ".OO..OO.",
        ".OUUUUO.",
        "..UZUZU.",
        "..UUUUU.",
        "..UZZUU.",
        ".UUUUUUU",
        "UUUUUUUU",
        "UUUUUUUU",
        "UUUUUUUU",
        ".UUUUUU.",
        ".UU..UU.",
        ".OO..OO.",
        "........",
    ],
    "cave_bat": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "i......i",
        "ii.II.ii",
        "iiiIIiii",
        "iiIZZIii",
        ".iIIIIi.",
        "..i..i..",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "snake": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "....ff..",
        "...fZff.",
        "...ffffS",
        "....ff..",
        "..ff....",
        ".fF.....",
        ".fF..ff.",
        "..fFfFf.",
        "...ffF..",
        "........",
    ],
}


def sprite_rows(sprite_id: str) -> list[str] | None:
    """The sprite's 16 rows (8-row textures repeated), or None if there is no sprite."""
    rows = SPRITES.get(sprite_id)
    if rows is None:
        return None
    return rows * (HEIGHT // len(rows))


def sprite_rgba(sprite_id: str) -> bytes | None:
    """RGBA pixels, bottom row first (the order Kivy textures expect)."""
    rows = sprite_rows(sprite_id)
    if rows is None:
        return None
    pixels = bytearray()
    for row in reversed(rows):
        for letter in row:
            rgb = PALETTE[letter]
            pixels += bytes((*rgb, 255)) if rgb is not None else bytes(4)
    return bytes(pixels)
