"""Pixel-art sprites for the Kivy frontend, as data (no Kivy import, so tests can check it).

Each sprite is 8 pixels wide and 16 tall, the ~1:2 shape of a grid cell, and maps a
sprite id from the game (tile type, "depleted", "player", "gem", "bag" or an enemy
name) to rows of palette letters. "." is transparent. Textures with 8 rows repeat
them to fill 16. "gem" is drawn in grays so the game can tint it with the gem's color. Some sprites
have extra animation frames (FRAMES), shown at a low frame rate (FPS).
"""

WIDTH, HEIGHT = 8, 16

PALETTE = {
    ".": None,
    # grass, trees
    "G": (38, 112, 38),
    "g": (72, 158, 62),
    "y": (128, 204, 92),
    "T": (20, 78, 24),
    "t": (44, 128, 44),
    "w": (104, 64, 24),
    # path, dirt, sand, town
    "p": (150, 116, 62),
    "P": (122, 92, 46),
    "d": (110, 76, 42),
    "D": (80, 54, 30),
    "k": (192, 172, 112),
    "K": (160, 140, 90),
    "q": (124, 98, 54),
    "Q": (92, 72, 38),
    # rock, ore
    "R": (84, 84, 88),
    "r": (136, 136, 140),
    "h": (192, 192, 196),
    "o": (255, 212, 0),
    "a": (110, 200, 255),
    "A": (200, 240, 255),
    # water
    "b": (36, 104, 196),
    "B": (96, 164, 240),
    "n": (10, 30, 118),
    "N": (32, 62, 160),
    # cave
    "c": (44, 34, 24),
    "C": (64, 50, 34),
    "x": (74, 52, 26),
    "X": (36, 26, 12),
    # worked-out ground
    "e": (56, 46, 36),
    "E": (34, 28, 20),
    # buildings
    "m": (172, 122, 62),
    "M": (168, 40, 30),
    "z": (52, 30, 10),
    "$": (255, 204, 0),
    "W": (240, 240, 240),
    "L": (196, 196, 196),
    "l": (140, 140, 140),
    "v": (86, 60, 140),
    "V": (140, 110, 220),
    # people and creatures
    "H": (122, 70, 20),
    "s": (240, 190, 140),
    "u": (52, 92, 204),
    "j": (60, 50, 42),
    "Z": (12, 12, 12),
    "U": (120, 78, 36),
    "O": (82, 50, 22),
    "i": (120, 30, 160),
    "I": (176, 92, 220),
    "f": (90, 180, 50),
    "F": (50, 120, 30),
    "S": (220, 40, 40),
    # decorations
    "J": (255, 120, 180),
    "Y": (255, 225, 80),
    "1": (200, 120, 255),
    "2": (222, 212, 192),
    "3": (92, 172, 62),
    "4": (62, 162, 72),
    "5": (152, 152, 152),
    "6": (120, 222, 255),
    # animals
    "7": (232, 218, 196),
    "8": (196, 134, 74),
    "9": (250, 250, 240),
    "0": (230, 255, 130),
    "+": (255, 160, 170),
    "-": (230, 120, 40),
    "=": (240, 230, 120),
    "*": (150, 255, 200),
    "^": (230, 90, 60),
}

SPRITES = {
    # ── Ground (fills the cell) ───────────────────────────────────────────────
    "grass": [
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
        "GGGgGGGG",
        "GGGGGGGG",
        "GgGGGGGG",
        "GGGGGgGG",
        "GGGGGGGG",
    ],
    "tree": [
        "GGGtTGGG",
        "GGtttTGG",
        "GttTttTG",
        "GtttTttG",
        "ttTtttTt",
        "tTttTttT",
        "tttTtttt",
        "GtTttTtG",
        "GGtttTGG",
        "GGGwwGGG",
        "GGGwwGGG",
        "GGGwwGGG",
        "GGwwwwGG",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
    ],
    "path": [
        "pppppppp",
        "ppPppppp",
        "pppppPpp",
        "pppppppp",
        "pPpppppp",
        "ppppppPp",
        "pppPpppp",
        "pppppppp",
    ],
    "rock": [
        "RRRRRRRR",
        "RRRhRRRR",
        "RRhrrRRR",
        "RhrrrrRR",
        "hrrrrrrR",
        "rrrRrrrr",
        "rrRRRrrr",
        "RRRRRRRR",
        "RRRRRhRR",
        "RRRRhrrR",
        "RRRhrrrr",
        "RRhrrrRr",
        "RhrrrRRr",
        "hrrrrrrr",
        "rrrrrrrr",
        "RRRRRRRR",
    ],
    "ore": [
        "rrrrrrrr",
        "rroRrrrr",
        "rRoorrrr",
        "rrrrrrRr",
        "rrrrroor",
        "rrRrrorr",
        "rrrrrrrr",
        "rRrrrrRr",
    ],
    "dirt": [
        "dddddddd",
        "ddDddddd",
        "ddddddDd",
        "dddddddd",
        "dDdddddd",
        "dddddDdd",
        "ddDddddd",
        "dddddddd",
    ],
    "shallow": [
        "bbbbbbbb",
        "bbBBbbbb",
        "bbbbbbbb",
        "bbbbbBBb",
        "bbbbbbbb",
        "bBBbbbbb",
        "bbbbbbbb",
        "bbbbBBbb",
    ],
    "bank": [
        "kkkkkkkk",
        "kKkkkkkk",
        "kkkkkKkk",
        "kkkkkkkk",
        "kkKkkkkk",
        "kkkkkkKk",
        "kkkkkkkk",
        "Kkkkkkkk",
    ],
    "deep": [
        "nnnnnnnn",
        "nnNNnnnn",
        "nnnnnnnn",
        "nnnnnNNn",
        "nnnnnnnn",
        "nNNnnnnn",
        "nnnnnnnn",
        "nnnnNNnn",
    ],
    "cave_floor": [
        "cccccccc",
        "cCcccccc",
        "ccccccCc",
        "cccccccc",
        "cccCcccc",
        "cccccccc",
        "cCcccccC",
        "cccccccc",
    ],
    "cave_wall": [  # rough rock, no regular courses
        "XxxXXxxX",
        "xxXxxxXx",
        "XxxxXxxx",
        "xXxxxxXX",
        "xxXXxxxx",
        "XxxxxXxx",
        "xxXxxxxX",
        "XxxXxxXx",
    ],
    "rich_ore": [
        "cccccccc",
        "ccAccccc",
        "caaacccc",
        "ccaccCcc",
        "cccccAcc",
        "ccccaaac",
        "cCcccacc",
        "cccccccc",
    ],
    "town": [
        "qqqqqqqQ",
        "qqqqqqqQ",
        "qqqqqqqQ",
        "QQQQQQQQ",
        "qqqQqqqq",
        "qqqQqqqq",
        "qqqQqqqq",
        "QQQQQQQQ",
    ],
    "shop": [
        "qqqqqqqq",
        "qqqqqqqq",
        "qqMMMMqq",
        "qMMMMMMq",
        "MMMMMMMM",
        "mmmmmmmm",
        "mWWmm$$m",
        "mWWmm$$m",
        "mmmmmmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
    ],
    "lapidary": [
        "qqqqqqqq",
        "qqqqqqqq",
        "qqvvvvqq",
        "qvvvvvvq",
        "vvvvvvvv",
        "mmmmmmmm",
        "mmmVVmmm",
        "mmVVVVmm",
        "mmmVVmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "mmmzzmmm",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
    ],
    "save": [
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqWqqqq",
        "qqqWWqqq",
        "qqqWWWqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqqWqqqq",
        "qqLLLLqq",
        "qLllllLq",
        "qqqqqqqq",
        "qqqqqqqq",
        "qqqqqqqq",
    ],
    "mineable_grass": [
        "GGGGGGGG",
        "GGGyyGGG",
        "GGygGyGG",
        "GygGGgyG",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
        "GGGGGGGG",
    ],
    "mineable_dirt": [
        "dddddddd",
        "ddDddDdd",
        "dddDDddd",
        "dddDDddd",
        "ddDddDdd",
        "dddddddd",
        "dDdddddd",
        "dddddddd",
    ],
    "mineable_rock": [
        "rrrrrrrr",
        "rrRrrrrr",
        "rrrRrrhr",
        "rRrrRrrr",
        "rrRrrRrr",
        "rhrrrrRr",
        "rrrrrRrr",
        "rrrrrrrr",
    ],
    "stream": [
        "bbbbbbbb",
        "bBBbbbbb",
        "bbbBBbbb",
        "bbbbbBBb",
        "bbbbbbbb",
        "bBBbbbbb",
        "bbbBBbbb",
        "bbbbbBBb",
    ],
    "lake": [
        "NNNNNNNN",
        "NNbNNNNN",
        "NNNNNNNN",
        "NNNNNbNN",
        "NNNNNNNN",
        "NbNNNNNN",
        "NNNNNNNN",
        "NNNNbNNN",
    ],
    "depleted": [
        "eeeeeeee",
        "eeEeeeee",
        "eEEEeeee",
        "eeEeeeEe",
        "eeeeeEEE",
        "eeeeeeEe",
        "eeEeeeee",
        "eeeeeeee",
    ],
    # ── Decorations (game/decor.py): ground with something growing on it ──────
    "flowers": [
        "GGGGGGGG",
        "GGJGGGGG",
        "GJYJGGGG",
        "GtJGGGGG",
        "GtGGGJGG",
        "GGGGJYJG",
        "GGGGGJGG",
        "GGGGGtGG",
    ],
    "flowers_yellow": [
        "GGGGGGGG",
        "GGGGGYGG",
        "GGGGYWYG",
        "GYGGGYGG",
        "YWYGGtGG",
        "GYGGGGGG",
        "GtGGGGGG",
        "GGGGGGGG",
    ],
    "mushroom": [
        "cccccccc",
        "cccccccc",
        "ccc111cc",
        "cc11111c",
        "cc1W11Wc",
        "cccc2ccc",
        "cccc2ccc",
        "ccCc2ccc",
        "cccccccc",
        "c11ccccc",
        "1111cccc",
        "c22ccccc",
        "c2cccccc",
        "cccccccc",
        "cccccCcc",
        "cccccccc",
    ],
    "crystal": [
        "cccccccc",
        "cccc6ccc",
        "ccc666cc",
        "ccc6W6cc",
        "cc66666c",
        "c66c6c6c",
        "c6ccccCc",
        "cccccccc",
    ],
    "reeds": [
        "k3kkk3kk",
        "k3kk33kk",
        "33kk3kkk",
        "k3kk3kk3",
        "k3k33kk3",
        "kk3k3kk3",
        "kk3k3k33",
        "KkkKkkkk",
    ],
    "lily": [
        "bbbbbbbb",
        "bb44bbbb",
        "b4444bbb",
        "b44J4bbb",
        "bb44bbbb",
        "bbbbbBBb",
        "bbbbbbbb",
        "bBBbbbbb",
    ],
    "pebbles": [
        "dddddddd",
        "dd5ddddd",
        "d555dddd",
        "dddddd5d",
        "ddddd55d",
        "dDdddddd",
        "ddd5dddd",
        "dddddddd",
    ],
    # ── Landmarks (game/landmarks.py), drawn on their ground ──────────────────
    "campfire": [
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGG$GGG",
        "GGG$S$GG",
        "GG$SYS$G",
        "GG$SYS$G",
        "GGwwwwwG",
        "GwwGGwwG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
    ],
    "tent": [
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGG8GGG",
        "GGG878GG",
        "GG87778G",
        "GG87778G",
        "G8777778",
        "G8778778",
        "877ZZ778",
        "877ZZ778",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
    ],
    "well": [
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGwwwGG",
        "GGwGGGwG",
        "GGwGGGwG",
        "GrrrrrrG",
        "rRRRRRRr",
        "rRbbbbRr",
        "rRbBbbRr",
        "rRRRRRRr",
        "GrrrrrrG",
        "GGGGGGGG",
        "GgGGGGgG",
        "GGGGGGGG",
        "GGGGGGGG",
        "GGGGGGGG",
    ],
    "cart": [
        "dddddddd",
        "dddddddd",
        "dddddddd",
        "dddddddd",
        "dRRRRRRd",
        "dR5r5rRd",
        "dUUUUUUd",
        "dUOUUOUd",
        "dUUUUUUd",
        "dZddddZd",
        "ZlZddZlZ",
        "dZddddZd",
        "dddddddd",
        "Dddddddd",
        "dddddddd",
        "ddddDddd",
    ],
    "statue": [
        "dddddddd",
        "ddd55ddd",
        "ddd55ddd",
        "dd5555dd",
        "d5d55d5d",
        "ddd55ddd",
        "ddd55ddd",
        "dd5dd5dd",
        "dd5dd5dd",
        "drrrrrrd",
        "rRRRRRRr",
        "rRRRRRRr",
        "dddddddd",
        "dddDdddd",
        "dddddddd",
        "dddddddd",
    ],
    "boat": [
        "kkkkkkkk",
        "kkkkkkkk",
        "kkkkkkkk",
        "kkkkkkkk",
        "kkkkkkkk",
        "U8888888",
        "kU88888k",
        "kkUUUUkk",
        "kkkkkkkk",
        "kkkkkkkk",
        "kKkkkkkk",
        "kkkkkkkk",
        "kkkkkKkk",
        "kkkkkkkk",
        "kkkkkkkk",
        "kkkkkkkk",
    ],
    "shrine": [
        "cccccccc",
        "ccc6cccc",
        "cc666ccc",
        "cc6W6c6c",
        "c66666c6",
        "cc666c66",
        "cc6c6c6c",
        "crrrrrrc",
        "rRRRRRRr",
        "cccccccc",
        "cCcccccc",
        "cccccccc",
        "cccccccc",
        "ccccccCc",
        "cccccccc",
        "cccccccc",
    ],
    # ── Objects (drawn over the ground) ───────────────────────────────────────
    "player": [
        "........",
        "........",
        "..HHHH..",
        ".HHHHHH.",
        "..ssss..",
        "..sZsZ..",
        "..ssss..",
        "...ss...",
        ".uuuuuu.",
        "s.uuuu.s",
        "s.uuuu.s",
        "..uuuu..",
        "..jjjj..",
        "..j..j..",
        "..j..j..",
        ".ZZ..ZZ.",
    ],
    "gem": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "..WWWW..",
        ".WLWWLW.",
        "LLLLLLLL",
        ".LlLLlL.",
        "..lLLl..",
        "...ll...",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "bag": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "...UU...",
        "..U..U..",
        "...UU...",
        "..UUUU..",
        ".UUUUUU.",
        ".UUO$UU.",
        ".UUUUUU.",
        "..UUUU..",
        "........",
        "........",
        "........",
    ],
    # ── Icons (floating event text) ───────────────────────────────────────────
    "heart": [
        "........",
        "........",
        "........",
        "........",
        "........",
        ".SS..SS.",
        "SWSSSSSS",
        "SSSSSSSS",
        "SSSSSSSS",
        ".SSSSSS.",
        "..SSSS..",
        "...SS...",
        "........",
        "........",
        "........",
        "........",
    ],
    # ── Animals (game/critters.py) ────────────────────────────────────────────
    "rabbit": [
        "........",
        "........",
        "........",
        "........",
        ".7....7.",
        ".7....7.",
        ".77..77.",
        "..7777..",
        ".7Z77Z7.",
        ".777+77.",
        "..7777..",
        ".777777.",
        "77777777",
        ".77..77.",
        "........",
        "........",
    ],
    "deer": [
        "........",
        "........",
        "........",
        "........",
        "O.O.....",
        ".OO.....",
        ".88.....",
        "8Z8.....",
        ".888888.",
        ".8888888",
        ".8888888",
        ".8.8..8.",
        ".8.8..8.",
        ".O.O..O.",
        "........",
        "........",
    ],
    "bird": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "9......9",
        "99....99",
        ".999999.",
        "..9Z99..",
        "...99...",
        "........",
        "........",
        "........",
        "........",
    ],
    "frog": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        ".33..33.",
        "3Z3333Z3",
        "33333333",
        ".333333.",
        "3.3333.3",
        "33....33",
        "........",
        "........",
    ],
    "fish": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        ".6666..6",
        "6Z66666.",
        ".6666..6",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "firefly": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "...0....",
        "..000...",
        "...0....",
        "........",
        "......0.",
        ".....000",
        "......0.",
        "........",
        "........",
        "........",
        "........",
    ],
    "beetle": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "..i..i..",
        "...ii...",
        ".iIIIIi.",
        "iIIiiIIi",
        ".iIIIIi.",
        "i.iiii.i",
        "........",
        "........",
        "........",
    ],
    "dog": [  # companion (game/dog.py)
        "........",
        "........",
        "........",
        "........",
        "........",
        "......O.",
        ".....88O",
        ".....8Z8",
        "O....888",
        ".8888888",
        ".888888.",
        ".88888..",
        ".8..8.8.",
        ".8..8.8.",
        ".O..O.O.",
        "........",
    ],
    "butterfly": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "J.....J.",
        "JJ...JJ.",
        "JYJ.JYJ.",
        ".JJZJJ..",
        "..JZJ...",
        ".JJ.JJ..",
        "J.....J.",
        "........",
        "........",
        "........",
        "........",
    ],
    "duck": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "...==...",
        "..=Z=-..",
        "...===..",
        "========",
        ".=====..",
        "..===...",
        "........",
        "........",
        "........",
    ],
    "owl": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "..UUUU..",
        ".U9UU9U.",
        ".UZUUZU.",
        ".UU--UU.",
        "..UUUU..",
        "..U77U..",
        "..U77U..",
        "...--...",
        "........",
        "........",
        "........",
    ],
    "fox": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "......-.",
        ".....--.",
        "-.....-Z",
        "--.-----",
        "--------",
        ".-------",
        "..-...-.",
        "..Z...Z.",
        "........",
        "........",
    ],
    "goat": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "7.7.....",
        "77......",
        ".777....",
        "7Z77....",
        ".7777777",
        ".7777777",
        ".7.7..7.",
        ".Z.Z..Z.",
        "........",
        "........",
    ],
    "crab": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "^.....^.",
        "^^...^^.",
        ".^^^^^..",
        "^^Z^Z^^.",
        ".^^^^^..",
        "^.^.^.^.",
        "........",
        "........",
    ],
    "glowworm": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "....*...",
        "...***..",
        "....*...",
        "........",
        "*.......",
        "........",
        "........",
        "........",
        "........",
    ],
    # ── Tools (swing animations, shop icons) ─────────────────────────────────
    "tool_shovel": [
        "...LL...",
        "..LLLL..",
        "..LhLL..",
        "..LLLL..",
        "...LL...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "..wwww..",
        "..w..w..",
        "........",
        "........",
    ],
    "tool_pickaxe": [
        "........",
        ".lLLLLl.",
        "l..ww..l",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "...ww...",
        "........",
        "........",
        "........",
    ],
    "tool_gold_pan": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        ".llllll.",
        "lLooLLLl",
        "lLLLoLLl",
        ".llllll.",
        "...ww...",
        "...ww...",
        "...ww...",
        "........",
        "........",
        "........",
    ],
    "tool_drill": [
        "...ll...",
        "...LL...",
        "...ll...",
        "..LLLL..",
        ".YYYYYY.",
        ".YZYYZY.",
        ".YYYYYY.",
        ".YYYYYY.",
        "..lwwl..",
        "...ww...",
        "...ww...",
        "...ww...",
        "........",
        "........",
        "........",
        "........",
    ],
    # ── Shop icons ───────────────────────────────────────────────────────────
    "icon_lantern": [
        "........",
        "........",
        "........",
        "........",
        "..llll..",
        "...ll...",
        ".llllll.",
        ".lYooYl.",
        ".lYooYl.",
        ".lYooYl.",
        ".llllll.",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_armor": [
        "........",
        "........",
        "........",
        "........",
        "l......l",
        "llRRRRll",
        ".lRhhRl.",
        ".lRRRRl.",
        ".lRhhRl.",
        ".lRRRRl.",
        "..llll..",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_boots": [
        "........",
        "........",
        "........",
        "........",
        "..UU....",
        "..UU....",
        "..UU....",
        "..UU....",
        "..UUUU..",
        "..UUUUU.",
        "..OOOOO.",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_rod": [
        "........",
        "........",
        "........",
        "U.....U.",
        ".U...U..",
        "..U.U...",
        "...U....",
        "...U....",
        "...U....",
        "...U....",
        "...U....",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_charm": [
        "........",
        "........",
        "........",
        "...$$...",
        "..$..$..",
        "..$..$..",
        "...$$...",
        "..VVVV..",
        ".VVWVVV.",
        ".VVVVVV.",
        "..VVVV..",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_bandage": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        ".WWWWWW.",
        ".WLSSLW.",
        ".WSSSSW.",
        ".WLSSLW.",
        ".WWWWWW.",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_oil": [
        "........",
        "........",
        "........",
        "........",
        "...ll...",
        "..llll..",
        ".looool.",
        ".loooool",
        ".loooool",
        ".loooool",
        "..llll..",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_contract": [
        "........",
        "........",
        "........",
        ".kkkkkk.",
        ".kKKKKk.",
        ".kkkkkk.",
        ".kKKKkk.",
        ".kkkkkk.",
        ".kKKKKk.",
        ".kkkk$k.",
        ".kkkkkk.",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_clover": [
        "........",
        "........",
        "........",
        "........",
        "..33.33.",
        ".3333333",
        ".33f3333",
        "..33f33.",
        ".333333.",
        "...3.33.",
        "...3....",
        "..3.....",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_night_pin": [
        "........",
        "........",
        "........",
        "........",
        "...YY...",
        "..Y..Y..",
        ".Y....Y.",
        "..Y..Y..",
        "...YY...",
        "...ll...",
        "...ll...",
        "...l....",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_scale": [
        "........",
        "........",
        "........",
        "........",
        "...$....",
        "$$$$$$$.",
        "$..$..$.",
        "$..$..$.",
        "$$.$.$$.",
        "...$....",
        "..$$$...",
        ".$$$$$..",
        "........",
        "........",
        "........",
        "........",
    ],
    "icon_feather": [
        "........",
        "........",
        "........",
        "........",
        ".....W..",
        "....WW..",
        "...WLW..",
        "..WLW...",
        ".WLW....",
        ".LW.....",
        "l.......",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "bear": [
        "........",
        "........",
        "........",
        ".OO..OO.",
        ".OUUUUO.",
        "..UZUZU.",
        "..UUUUU.",
        "..UZZUU.",
        ".UUUUUUU",
        "UUUUUUUU",
        "UUUUUUUU",
        "UUUUUUUU",
        ".UUUUUU.",
        ".UU..UU.",
        ".OO..OO.",
        "........",
    ],
    "cave_bat": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "i......i",
        "ii.II.ii",
        "iiiIIiii",
        "iiIZZIii",
        ".iIIIIi.",
        "..i..i..",
        "........",
        "........",
        "........",
        "........",
        "........",
    ],
    "snake": [
        "........",
        "........",
        "........",
        "........",
        "........",
        "........",
        "....ff..",
        "...fZff.",
        "...ffffS",
        "....ff..",
        "..ff....",
        ".fF.....",
        ".fF..ff.",
        "..fFfFf.",
        "...ffF..",
        "........",
    ],
}


# ── Animation ─────────────────────────────────────────────────────────────────
# Extra frames after the sprite itself (frame 0). Pixel art reads well at a low frame
# rate; cells get a phase offset so neighbouring trees or waves do not move in step.


def _shifted(rows: list[str], step: int) -> list[str]:
    """Each row rotated ``step`` pixels to the right (flowing water)."""
    return [row[-step:] + row[:-step] for row in rows]


def _swap(rows: list[str], changes: dict) -> list[str]:
    """A copy of ``rows`` with whole rows replaced: {row index: new row}."""
    return [changes.get(i, row) for i, row in enumerate(rows)]


FRAMES = {
    "stream": [_shifted(SPRITES["stream"], n) for n in (2, 4, 6)],
    "shallow": [_shifted(SPRITES["shallow"], n) for n in (2, 4, 6)],
    "lake": [_shifted(SPRITES["lake"], 1)],
    "deep": [_shifted(SPRITES["deep"], 1)],
    "tree": [  # the canopy leans one pixel
        _swap(SPRITES["tree"], {i: "G" + SPRITES["tree"][i][:-1] for i in range(0, 9)}),
    ],
    "rich_ore": [_swap(SPRITES["rich_ore"], {1: "cccccccc", 4: "cccccWcc"})],  # glint
    "gem": [  # sparkle, then rest
        _swap(SPRITES["gem"], {4: "..W.....", 5: "..WWWW.."}),
        SPRITES["gem"],
        SPRITES["gem"],
    ],
    "player": [  # breathing: the body dips one pixel
        ["........"] + SPRITES["player"][:12] + SPRITES["player"][13:],
        # walking: two poses (frames 2 and 3); WALK mirrors them for the other leg
        _swap(
            SPRITES["player"],
            {9: "s.uuuu..", 10: "..uuuus.", 13: ".j...j..", 14: "j.....j.", 15: "ZZ....ZZ"},
        ),
        _swap(SPRITES["player"], {13: "...jj...", 14: "...jj...", 15: "..ZZZZ.."}),
        # idle fidgets: blink (frame 4), glance aside (frame 5)
        _swap(SPRITES["player"], {5: "..ssss.."}),
        _swap(SPRITES["player"], {5: "..ZsZs.."}),
    ],
    "bear": [["........"] + SPRITES["bear"][:15]],
    "cave_bat": [  # wings up
        _swap(
            SPRITES["cave_bat"],
            {4: "i......i", 5: "ii....ii", 6: ".i.II.i.", 7: "..iIIi.."},
        ),
    ],
    "snake": [_swap(SPRITES["snake"], {8: "...ffff.", 7: "...fZffS"})],  # tongue
    "rabbit": [
        ["........"] * 2 + SPRITES["rabbit"][:14],  # hop
        _swap(SPRITES["rabbit"], {9: ".77+777."}),  # sniffing (frame 2)
    ],
    "deer": [
        _swap(SPRITES["deer"], {11: ".8..8.8.", 12: ".8..8.8.", 13: ".O..O.O."}),
        # grazing: head down (frame 2)
        _swap(
            SPRITES["deer"],
            {
                4: "........",
                5: "........",
                6: "........",
                7: "........",
                10: "8Z888888",
                11: "88.8..8.",
                12: "O..8..8.",
                13: "...O..O.",
            },
        ),
    ],
    "bird": [_swap(SPRITES["bird"], {7: "........", 8: "99....99", 9: ".999999."})],
    "frog": [_swap(SPRITES["frog"], {13: ".3....3.", 12: ".333333."})],
    "fish": [_shifted(SPRITES["fish"], 1)],
    "firefly": [_swap(SPRITES["firefly"], {5: "........", 6: "...0....", 7: "........"})],
    "beetle": [_swap(SPRITES["beetle"], {12: ".i.ii.i."})],
    "campfire": [_swap(SPRITES["campfire"], {6: "GGG$GGGG", 7: "GG$S$$GG", 8: "GG$YSS$G"})],
    "butterfly": [
        _swap(
            SPRITES["butterfly"],
            {
                5: "........",
                6: ".J...J..",
                7: "JYJ.JYJ.",
                8: ".JJZJJ..",
                10: ".J...J..",
                11: "........",
            },
        )
    ],
    "duck": [_shifted(SPRITES["duck"], 1)],
    "owl": [_swap(SPRITES["owl"], {6: ".UZUUUU.", 7: ".UZUUZU."})],
    "fox": [_swap(SPRITES["fox"], {12: ".-...-..", 13: ".Z...Z.."})],
    "goat": [_swap(SPRITES["goat"], {12: "..7.7.7.", 13: "..Z.Z.Z."})],
    "crab": [_swap(SPRITES["crab"], {8: "........", 9: "^^...^^."})],
    "glowworm": [_swap(SPRITES["glowworm"], {7: "........", 8: "...*....", 9: "..***..."})],
    "dog": [
        _swap(SPRITES["dog"], {12: "..8.8..8", 13: "..8.8..8", 14: "..O.O..O", 8: "O....888"}),
        _swap(SPRITES["dog"], {7: "O....8Z8", 8: ".....888"}),  # tail wag (frame 2)
    ],
}
FPS = {"stream": 4, "shallow": 4, "lake": 2, "deep": 2, "tree": 1, "rich_ore": 2,
       "gem": 3, "player": 2, "bear": 2, "cave_bat": 6, "snake": 2, "rabbit": 2,
       "deer": 1, "bird": 6, "frog": 1, "fish": 3, "firefly": 3, "beetle": 4, "dog": 2,
       "campfire": 5, "butterfly": 6, "duck": 2, "owl": 1, "fox": 2, "goat": 1,
       "crab": 2, "glowworm": 2}  # fmt: skip


# Frames shown while a thing moves, as (frame, mirrored) at WALK_FPS. The player's
# walk is "draw two, mirror two": both poses, then both mirrored for the other leg.
WALK_FPS = 8
WALK = {"player": [(2, False), (3, False), (2, True), (3, True)]}
for _name in (
    "rabbit",
    "deer",
    "bear",
    "snake",
    "frog",
    "fish",
    "beetle",
    "bird",
    "cave_bat",
    "dog",
):
    WALK[_name] = [(0, False), (1, False)]
# Frames of the idle cycle, where they are not all of the sprite's frames.
IDLE = {"player": [0, 1], "deer": [0, 1], "rabbit": [0, 1], "dog": [0, 1]}
# Idle variety: a blink now and then (BLINK) and, after standing still a while, a
# special idle (SPECIAL, shown in a slow cycle with pauses).
BLINK = {"player": 4}
SPECIAL = {"player": [5, 0, 5], "deer": [2, 2, 2, 0], "rabbit": [2, 0, 2], "dog": [2, 0, 2, 0]}
# Which way a sprite looks as drawn (1 = right, -1 = left, 0 = symmetric): it is
# mirrored to face the way it moves.
FACING = {"deer": -1, "fish": -1, "snake": 1, "dog": 1, "duck": -1, "fox": 1, "goat": -1}


# Depth: fliers are drawn above their shadow (gap = altitude, in cells); hoppers rise
# along an arc as they step between cells (peak height, in cells); things in water or
# that glow cast no shadow.
ALTITUDE = {"bird": 0.45, "butterfly": 0.35, "cave_bat": 0.4}
HOP = {"rabbit": 0.3, "frog": 0.35, "goat": 0.15, "deer": 0.12, "fox": 0.1, "dog": 0.1,
       "player": 0.06}  # fmt: skip
NO_SHADOW = {"fish", "duck", "firefly", "glowworm"}


def depth(sprite_id: str) -> tuple:
    """(altitude, hop height, casts a shadow) for a sprite."""
    base = _base(sprite_id)
    return ALTITUDE.get(base, 0.0), HOP.get(base, 0.0), base not in NO_SHADOW


SPECIAL_AFTER = 8.0  # seconds standing still before special idles start
SPECIAL_FPS = 1.5
SPECIAL_PAUSE = 6  # cycle steps of plain idle between two special idles
BLINK_SECONDS = 0.15


def idle_frame(sprite_id: str, seconds: float, still_for: float, blinking: bool, phase=0):
    """Frame of a standing sprite: a blink, a special idle after a while, or its idle."""
    base = _base(sprite_id)
    if blinking and base in BLINK:
        return BLINK[base]
    special = SPECIAL.get(base)
    if special and still_for >= SPECIAL_AFTER:
        step = int((still_for - SPECIAL_AFTER) * SPECIAL_FPS) % (len(special) + SPECIAL_PAUSE)
        if step < len(special):
            return special[step]
    return frame_at(sprite_id, seconds, phase)


def walk_frame(sprite_id: str, seconds: float, phase: int = 0):
    """(frame, mirrored) to show while the sprite moves, or None if it has no walk."""
    cycle = WALK.get(_base(sprite_id))
    if cycle is None:
        return None
    return cycle[(int(seconds * WALK_FPS) + phase) % len(cycle)]


# Outfits (game catalogs.toml [[outfits]]): palette swaps of the player, as
# {letter in the player sprite: letter to draw instead} (H hat, u shirt, j trousers).
OUTFIT_PALETTES = {
    "miner": {"H": "Y", "u": "8"},
    "ranger": {"H": "U", "u": "3", "j": "O"},
    "night": {"H": "Z", "u": "v", "j": "Z"},
    "royal": {"H": "$", "u": "V", "j": "v"},
}


def _base(sprite_id: str) -> str:
    """The sprite an id is drawn from: "stream#5" is a stream with shore on N and S,
    "player~miner" the player in the miner's outfit."""
    return sprite_id.split("#", 1)[0].split("~", 1)[0]


def facing(sprite_id: str) -> int:
    return FACING.get(_base(sprite_id), 0)


def _shore(rows: list[str], mask: int) -> list[str]:
    """Foam along the sides that touch land (bits N=1, E=2, S=4, W=8): a solid line
    at the edge and a dotted one inside it."""
    grid = [list(row) for row in rows]
    h, w = len(grid), len(grid[0])
    for i in range(max(h, w)):
        dotted = "A" if i % 2 == 0 else None
        if mask & 1 and i < w:
            grid[0][i] = "A"
            grid[1][i] = dotted or grid[1][i]
        if mask & 4 and i < w:
            grid[h - 1][i] = "A"
            grid[h - 2][i] = dotted or grid[h - 2][i]
        if mask & 8 and i < h:
            grid[i][0] = "A"
            grid[i][1] = dotted or grid[i][1]
        if mask & 2 and i < h:
            grid[i][w - 1] = "A"
            grid[i][w - 2] = dotted or grid[i][w - 2]
    return ["".join(row) for row in grid]


_cycles: dict = {}  # sprite id -> (idle frames, fps), worked out once per id


def frame_count(sprite_id: str) -> int:
    return 1 + len(FRAMES.get(_base(sprite_id), ()))


def frame_at(sprite_id: str, seconds: float, phase: int = 0) -> int:
    """Which frame of the sprite shows at time ``seconds`` (``phase`` shifts a cell's cycle)."""
    cycle = _cycles.get(sprite_id)
    if cycle is None:
        base = _base(sprite_id)
        frames = tuple(IDLE.get(base) or range(frame_count(base)))
        cycle = _cycles[sprite_id] = (frames, FPS.get(base, 1))
    frames, fps = cycle
    if len(frames) == 1:  # most sprites stand still: answer at once
        return 0
    return frames[(int(seconds * fps) + phase) % len(frames)]


def sprite_rows(sprite_id: str, frame: int = 0) -> list[str] | None:
    """The sprite's 16 rows (8-row textures repeated), or None if there is no sprite."""
    base = _base(sprite_id)
    rows = SPRITES.get(base)
    if rows is None:
        return None
    if frame:
        rows = FRAMES[base][frame - 1]
    rows = rows * (HEIGHT // len(rows))
    if "#" in sprite_id:
        rows = _shore(rows, int(sprite_id.split("#", 1)[1]))
    if "~" in sprite_id:
        swap = OUTFIT_PALETTES[sprite_id.split("~", 1)[1]]
        rows = ["".join(swap.get(letter, letter) for letter in row) for row in rows]
    return rows


def sprite_rgba(sprite_id: str, frame: int = 0) -> bytes | None:
    """RGBA pixels, bottom row first (the order Kivy textures expect)."""
    rows = sprite_rows(sprite_id, frame)
    if rows is None:
        return None
    pixels = bytearray()
    for row in reversed(rows):
        for letter in row:
            rgb = PALETTE[letter]
            pixels += bytes((*rgb, 255)) if rgb is not None else bytes(4)
    return bytes(pixels)
